[remote.github]
owner = "randy3k"
repo = "radian"

[changelog]
header = """
# Changelog

"""
body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}\
{% else %}\
    ## Unreleased\
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}

    ### {{ group | upper_first }}    
    {% for commit in commits %}
        {% if commit.remote.pr_title -%}\
            {%- set commit_message = commit.remote.pr_title -%}\
        {%- else -%}\
            {%- set commit_message = commit.message -%}\
        {%- endif -%}
        * {{ commit_message | split(pat="\n") | first | trim }}\
            {% if commit.remote.pr_number %} \
            ([#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}))
            {%- endif %}\n
    {%- endfor -%}

{% endfor %}\
{% if version %}
    {% if previous.version %}
      **Full Changelog**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
    {% endif %}
{% else -%}
  {% raw %}\n{% endraw %}
{% endif %}\
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
trim = true
footer = """
<!-- generated by git-cliff -->
"""
postprocessors = []

[git]
conventional_commits = false
commit_parsers = [
    { message = "(?i)^feat\\b", group = "Features" },
    { message = "(?i)^fix\\b", group = "Bug Fixes" },
    { message = "(?i)^docs\\b", group = "Documentation" },
    { message = "(?i)^perf\\b", group = "Performance" },
    { message = "(?i)^refactor\\b", group = "Refactor" },
    { message = "(?i)^style\\b", group = "Styling" },
    { message = "(?i)^test\\b", group = "Testing" },
    { message = "(?i)^(chore|bump to)\\b", skip = true },
    { body = ".*", group = "Other" },
]
filter_commits = true
topo_order = false
sort_commits = "oldest"
